-- Data migrated from ncc.db (SQLite) -> run AFTER supabase_schema.sql


-- cadets (34 rows)
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (9, 'Shivam Hooda', 'UO', 'NCC-S01', '2024-27', NULL, 'C-01', NULL, NULL, 1, 'UO', 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (10, 'Sarthak Parihar', 'SUO', 'NCC-S02', '2024-27', NULL, 'C-02', NULL, NULL, 1, 'SUO', 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (11, 'Shivanshu Bisht', 'UO', 'NCC-S03', '2024-27', NULL, 'C-03', NULL, NULL, 1, 'UO', 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (12, 'Soham Tavre', 'CDT', 'NCC-S04', '2024-27', NULL, 'C-04', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (13, 'Ritul Kumar Singh', 'CDT', 'NCC-S05', '2024-27', NULL, 'C-05', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (14, 'Rahul Pal', 'CDT', 'NCC-S06', '2024-27', NULL, 'C-06', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (15, 'Harsh Saini', 'CDT', 'NCC-S07', '2024-27', NULL, 'C-07', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (16, 'Samaksh Parihar', 'CDT', 'NCC-S08', '2024-27', NULL, 'C-08', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (17, 'Lakshay Chauhan', 'SGT', 'NCC-S09', '2024-27', NULL, 'C-09', NULL, NULL, 1, 'SGT', 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (18, 'Kartik Chaudhary', 'CSM', 'NCC-S10', '2024-27', NULL, 'C-10', NULL, NULL, 1, 'CSM', 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (19, 'Kaushal Kumar', 'CDT', 'NCC-S11', '2024-27', NULL, 'C-11', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (20, 'Tushar Dhyani', 'CDT', 'NCC-S12', '2024-27', NULL, 'C-12', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (21, 'Bhawesh Singh Rawat', 'CDT', 'NCC-S13', '2024-27', NULL, 'C-13', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (22, 'Mayank Sharma', 'CPL', 'NCC-S14', '2024-27', NULL, 'C-14', NULL, NULL, 1, 'CPL', 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (23, 'Sailesh Singh', 'CDT', 'NCC-S15', '2024-27', NULL, 'C-15', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (24, 'Prince Kumar Sharma', 'CDT', 'NCC-S16', '2024-27', NULL, 'C-16', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (25, 'Aditya Raj Chauhan', 'CDT', 'NCC-S17', '2024-27', NULL, 'C-17', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (26, 'Asish Mehta', 'CPL', 'NCC-S18', '2024-27', NULL, 'C-18', NULL, NULL, 1, 'CPL', 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (27, 'Neeraj Kumar Verma', 'SGT', 'NCC-S19', '2024-27', NULL, 'C-19', NULL, NULL, 1, 'SGT', 1, '2026-03-07 14:30:00', 'NCC 3rd Year', 'Senior');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (28, 'Abhay Kumar Pandey', 'CDT', 'NCC-B01', '2025-28', NULL, 'C-20', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (29, 'Lokesh Kathayat', 'CDT', 'NCC-B02', '2025-28', NULL, 'C-21', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (30, 'Angad Niroula', 'CDT', 'NCC-B03', '2025-28', NULL, 'C-22', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (31, 'Divyansh Upadhyay', 'CDT', 'NCC-B04', '2025-28', NULL, 'C-23', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (32, 'Satyam Kumar', 'CDT', 'NCC-B05', '2025-28', NULL, 'C-24', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (33, 'Mradul Singh Chauhan', 'CDT', 'NCC-B06', '2025-28', NULL, 'C-25', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (34, 'Utsav Kumar', 'CDT', 'NCC-B07', '2025-28', NULL, 'C-26', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (35, 'Aniketh Singh', 'CDT', 'NCC-B08', '2025-28', NULL, 'C-27', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (36, 'Aman Thakur', 'CDT', 'NCC-B09', '2025-28', NULL, 'C-28', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (37, 'Aryan Singh Chauhan', 'CDT', 'NCC-B10', '2025-28', NULL, 'C-29', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (38, 'Aranya Raj', 'CDT', 'NCC-B11', '2025-28', NULL, 'C-30', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (39, 'Suraj Gupta', 'CDT', 'NCC-B12', '2025-28', NULL, 'C-31', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (40, 'Dev Kumar Verma', 'CDT', 'NCC-B13', '2025-28', NULL, 'C-32', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (41, 'Navdeep Singh Rathore', 'CDT', 'NCC-B14', '2025-28', NULL, 'C-33', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');
INSERT INTO cadets (id, name, rank, roll_number, batch, branch, chest_number, photo, bio, is_rank_holder, rank_position, active, created_at, ncc_year, category) VALUES (42, 'Utsav Anand', 'CDT', 'NCC-B15', '2025-28', NULL, 'C-34', NULL, NULL, 0, NULL, 1, '2026-03-07 14:30:00', 'NCC 2nd Year', 'Buddy');

-- rank_holders (8 rows)
INSERT INTO rank_holders (id, rank_code, rank_full, holder_name, description, sort_order) VALUES (8, 'SUO', 'Senior Under Officer', 'Sarthak Parihar', 'Senior-most cadet leader of the battalion. Oversees discipline, coordination with the ANO, and represents the unit at official parades.', 1);
INSERT INTO rank_holders (id, rank_code, rank_full, holder_name, description, sort_order) VALUES (9, 'UO', 'Under Officer', 'Shivam Hooda', 'Assists the SUO in commanding the battalion and leads fall-in drill for senior cadets.', 2);
INSERT INTO rank_holders (id, rank_code, rank_full, holder_name, description, sort_order) VALUES (10, 'UO', 'Under Officer', 'Shivanshu Bisht', 'Assists the SUO in commanding the battalion and coordinates training schedules.', 3);
INSERT INTO rank_holders (id, rank_code, rank_full, holder_name, description, sort_order) VALUES (11, 'CSM', 'Company Sergeant Major', 'Kartik Chaudhary', 'Senior NCO responsible for discipline, attendance and coordination across all cadet companies.', 4);
INSERT INTO rank_holders (id, rank_code, rank_full, holder_name, description, sort_order) VALUES (12, 'CPL', 'Corporal', 'Mayank Sharma', 'Leads a section of cadets and assists in drill instruction and daily fall-in.', 5);
INSERT INTO rank_holders (id, rank_code, rank_full, holder_name, description, sort_order) VALUES (13, 'CPL', 'Corporal', 'Asish Mehta', 'Leads a section of cadets and assists in drill instruction and daily fall-in.', 6);
INSERT INTO rank_holders (id, rank_code, rank_full, holder_name, description, sort_order) VALUES (14, 'SGT', 'Sergeant', 'Neeraj Kumar Verma', 'Supervises section-level training and reports attendance to the CSM.', 7);
INSERT INTO rank_holders (id, rank_code, rank_full, holder_name, description, sort_order) VALUES (15, 'SGT', 'Sergeant', 'Lakshay Chauhan', 'Supervises section-level training and reports attendance to the CSM.', 8);

-- alumni (4 rows)
INSERT INTO alumni (id, name, rank, batch_year, achievements, current_profession, photo, testimonial) VALUES (1, 'Lt. Aditya Kumar', 'SUO', '2018-21', 'Best Cadet Award, Republic Day Parade 2021', 'Indian Army Officer', NULL, NULL);
INSERT INTO alumni (id, name, rank, batch_year, achievements, current_profession, photo, testimonial) VALUES (2, 'Capt. Neha Verma', 'JUO', '2017-20', 'State Level Shooting Champion, NCC C Certificate', 'Software Engineer, Infosys', NULL, NULL);
INSERT INTO alumni (id, name, rank, batch_year, achievements, current_profession, photo, testimonial) VALUES (3, 'Rajesh Dimri', 'CSM', '2019-22', 'Best Drill Award, CATC Camp Winner', 'IPS Officer', NULL, NULL);
INSERT INTO alumni (id, name, rank, batch_year, achievements, current_profession, photo, testimonial) VALUES (4, 'Sunita Negi', 'Cadet', '2020-23', 'Trekking Expedition Lead, Social Service Award', 'Entrepreneur', NULL, NULL);

-- achievements (6 rows)
INSERT INTO achievements (id, title, description, year, category) VALUES (1, 'Best Cadet Award', 'Top cadet of the year for excellence in training and academics.', 2024, 'award');
INSERT INTO achievements (id, title, description, year, category) VALUES (2, 'Republic Day Parade', 'Selected cadets marched at the national Republic Day Parade, New Delhi.', 2024, 'parade');
INSERT INTO achievements (id, title, description, year, category) VALUES (3, 'C Certificate Excellence', 'Multiple cadets secured A grade in the C certificate examination.', 2023, 'academic');
INSERT INTO achievements (id, title, description, year, category) VALUES (4, 'Thal Sainik Camp', 'Won the inter-unit skills competition at TSC.', 2023, 'camp');
INSERT INTO achievements (id, title, description, year, category) VALUES (5, 'Best Drill Trophy', 'Inter-college drill competition champions.', 2024, 'drill');
INSERT INTO achievements (id, title, description, year, category) VALUES (6, 'Social Service Award', 'Recognised for disaster relief participation in Uttarakhand floods.', 2023, 'service');

-- events (3 rows)
INSERT INTO events (id, title, description, event_type, event_date, location, created_at) VALUES (1, 'Weekly Fall-In Parade', 'Mandatory weekly parade. Full uniform required.', 'fallin', '2025-03-15', 'DIT University Parade Ground', '2026-03-07 13:42:32');
INSERT INTO events (id, title, description, event_type, event_date, location, created_at) VALUES (2, 'Annual Camp Selection', 'Selection for Annual Training Camp 2025.', 'camp', '2025-04-01', 'NCC Training Center, Dehradun', '2026-03-07 13:42:32');
INSERT INTO events (id, title, description, event_type, event_date, location, created_at) VALUES (3, 'Republic Day Drill Prep', 'Intensive training for Republic Day selection.', 'training', '2025-02-20', 'DIT University Parade Ground', '2026-03-07 13:42:32');
-- Re-sync auto-increment sequences after loading rows with explicit IDs
-- (without this, the next INSERT without an explicit id collides with
-- an id that already exists, since Postgres's sequence counter doesn't
-- know these rows were inserted)
SELECT setval(pg_get_serial_sequence('cadets','id'),        COALESCE((SELECT MAX(id) FROM cadets),1));
SELECT setval(pg_get_serial_sequence('rank_holders','id'),  COALESCE((SELECT MAX(id) FROM rank_holders),1));
SELECT setval(pg_get_serial_sequence('alumni','id'),        COALESCE((SELECT MAX(id) FROM alumni),1));
SELECT setval(pg_get_serial_sequence('achievements','id'),  COALESCE((SELECT MAX(id) FROM achievements),1));
SELECT setval(pg_get_serial_sequence('events','id'),        COALESCE((SELECT MAX(id) FROM events),1));
SELECT setval(pg_get_serial_sequence('gallery','id'),       COALESCE((SELECT MAX(id) FROM gallery),1));
